/**
 * 형식 프로필이 매핑하는 표준 필드 (canonical field).
 * 원본 엑셀의 제목(헤더)은 제각각이므로, 프로필이 "표준 필드 ← 제목 별칭 목록" 을 데이터로 가진다.
 */
export const CANONICAL_FIELDS = [
  // 공통
  'transactionDate',
  'approvalNumber',
  'supplyAmount',
  'vatAmount',
  'serviceCharge',
  'taxFreeAmount',
  'totalAmount',
  'description',
  'note',
  'transactionKind',
  'currency',
  'foreignAmount',
  'overseasFlag',
  'deductibleDecision',
  'deductibleNote',
  // 가맹점 / 상대방
  'merchantName',
  'merchantBusinessNumber',
  'merchantTaxType',
  'merchantBizType',
  'merchantCategory',
  'merchantCategoryCode',
  // 카드
  'cardCompany',
  'cardNumber',
  'installment',
  // 현금영수증
  'issueMethod',
  'userName',
  // 세금계산서
  'issueDate',
  'sendDate',
  'supplierBusinessNumber',
  'supplierSubNumber',
  'supplierName',
  'supplierRepresentative',
  'supplierAddress',
  'buyerBusinessNumber',
  'buyerSubNumber',
  'buyerName',
  'buyerRepresentative',
  'buyerAddress',
  'invoiceClass',
  'invoiceKind',
  'issueType',
  'receiptOrClaim',
  'supplierEmail',
  'buyerEmail1',
  'buyerEmail2',
  'itemDate',
  'itemName',
  'itemSpec',
  'itemQuantity',
  'itemUnitPrice',
  'itemSupplyAmount',
  'itemVatAmount',
  'itemNote',
  // WEHAGO 매입매출장 역수입
  'vatTypeCode',
  'directionLabel',
  'counterpartyCode',
  'debitAccount',
  'creditAccount',
  'managementNumber',
  'voucherStatus',
] as const;

export type CanonicalField = (typeof CANONICAL_FIELDS)[number];

/** 사용자에게 보여줄 필드 이름 */
export const FIELD_LABELS_KO: Record<CanonicalField, string> = {
  transactionDate: '거래일자',
  approvalNumber: '승인번호',
  supplyAmount: '공급가액',
  vatAmount: '부가세(세액)',
  serviceCharge: '봉사료',
  taxFreeAmount: '비과세',
  totalAmount: '합계',
  description: '적요/품목',
  note: '비고',
  transactionKind: '거래구분',
  currency: '통화',
  foreignAmount: '외화금액',
  overseasFlag: '국내/해외 구분',
  deductibleDecision: '공제여부',
  deductibleNote: '공제 비고',
  merchantName: '가맹점명/상호',
  merchantBusinessNumber: '가맹점 사업자번호',
  merchantTaxType: '가맹점 유형(과세유형)',
  merchantBizType: '업태',
  merchantCategory: '업종',
  merchantCategoryCode: '업종코드',
  cardCompany: '카드사',
  cardNumber: '카드번호',
  installment: '할부',
  issueMethod: '발급수단',
  userName: '사용자명',
  issueDate: '발급일자',
  sendDate: '전송일자',
  supplierBusinessNumber: '공급자 사업자등록번호',
  supplierSubNumber: '공급자 종사업장번호',
  supplierName: '공급자 상호',
  supplierRepresentative: '공급자 대표자명',
  supplierAddress: '공급자 주소',
  buyerBusinessNumber: '공급받는자 사업자등록번호',
  buyerSubNumber: '공급받는자 종사업장번호',
  buyerName: '공급받는자 상호',
  buyerRepresentative: '공급받는자 대표자명',
  buyerAddress: '공급받는자 주소',
  invoiceClass: '(세금)계산서 분류',
  invoiceKind: '(세금)계산서 종류',
  issueType: '발급유형',
  receiptOrClaim: '영수/청구 구분',
  supplierEmail: '공급자 이메일',
  buyerEmail1: '공급받는자 이메일1',
  buyerEmail2: '공급받는자 이메일2',
  itemDate: '품목일자',
  itemName: '품목명',
  itemSpec: '품목규격',
  itemQuantity: '품목수량',
  itemUnitPrice: '품목단가',
  itemSupplyAmount: '품목공급가액',
  itemVatAmount: '품목세액',
  itemNote: '품목비고',
  vatTypeCode: '유형(매입매출 유형)',
  directionLabel: '매입/매출 구분',
  counterpartyCode: '거래처코드',
  debitAccount: '차변계정',
  creditAccount: '대변계정',
  managementNumber: '관리',
  voucherStatus: '전표상태',
};

/** 어느 필드의 값이 금액인지 (rawData 스크럽 제외·금액 파싱 대상) */
export const AMOUNT_FIELDS: ReadonlySet<CanonicalField> = new Set<CanonicalField>([
  'supplyAmount',
  'vatAmount',
  'serviceCharge',
  'taxFreeAmount',
  'totalAmount',
  'itemSupplyAmount',
  'itemVatAmount',
  'itemUnitPrice',
]);

/** 민감정보 마스킹 대상에서 제외할 식별번호 필드 (주민번호 형태면 그래도 마스킹) */
export const IDENTIFIER_FIELDS: ReadonlySet<CanonicalField> = new Set<CanonicalField>([
  'approvalNumber',
  'supplierBusinessNumber',
  'buyerBusinessNumber',
  'merchantBusinessNumber',
  'supplierSubNumber',
  'buyerSubNumber',
  'merchantCategoryCode',
  'managementNumber',
  'counterpartyCode',
]);

export function fieldLabel(field: string): string {
  return (FIELD_LABELS_KO as Record<string, string>)[field] ?? field;
}
