import { mkdtempSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterAll, it } from 'vitest';
process.env.MINTAX_DATA_KEY = Buffer.alloc(32, 7).toString('base64');
process.env.MINTAX_INDEX_KEY = Buffer.alloc(32, 9).toString('base64');
process.env.STORAGE_LOCAL_DIR = mkdtempSync(path.join(os.tmpdir(), 'mintax-prof-'));
import { closeDb, payrollItems, payrollMonths, setupTestDatabase } from '@mintax/db';
import { createTestClient, createTestUser, testContext } from '../testing/factory';
import { applyPayrollRows, approveChanges, generatePayrollExports, importEmployees, markReadyForFiling, startPayrollMonth, validatePayrollMonth } from './index';
afterAll(() => closeDb());
it('profile', async () => {
  const db = await setupTestDatabase(process.env.DATABASE_URL_TEST);
  const staff = testContext(db, (await createTestUser(db, 'staff')).actor);
  const c = await createTestClient(db, { name: 'P' });
  const N = 600;
  let t = performance.now();
  const lap = (l: string) => { const n = performance.now(); console.log(l, Math.round(n - t)); t = n; };
  const imp = await importEmployees(staff, { clientId: c.id, rows: Array.from({ length: N }, (_, i) => ({ name: `직원${i}`, incomeType: '근로', idNumber: `${700101 + i}-1${String(100000 + i).slice(-6)}`, baseSalary: 2_000_000 + i, paymentDay: 25 })) });
  lap('import');
  const [m0] = await db.insert(payrollMonths).values({ clientId: c.id, period: '2026-08', paymentPeriod: '2026-08', status: 'confirmed', wizardStep: 7 }).returning();
  await db.insert(payrollItems).values(imp.employees.map((e) => ({ payrollMonthId: m0!.id, employeeId: e.id, incomeType: 'earned' as const, taxablePay: e.baseSalary, grossPay: e.baseSalary, incomeTax: 40000, localIncomeTax: 4000, netPay: e.baseSalary - 44000, paymentDate: '2026-08-25' })));
  lap('prev');
  const m = await startPayrollMonth(staff, { clientId: c.id, period: '2026-09' });
  lap('start');
  const r = await applyPayrollRows(staff, { payrollMonthId: m.id, rows: imp.employees.slice(0, 50).map((e) => ({ employeeId: e.id, taxablePay: e.baseSalary + 100000, incomeTax: 45000 })) });
  lap('apply');
  await approveChanges(staff, { payrollMonthId: m.id, itemIds: r.diff.changes.map((x) => x.itemId!) });
  lap('approve');
  await validatePayrollMonth(staff, m.id);
  lap('validate');
  await generatePayrollExports(staff, m.id);
  lap('exports');
  await markReadyForFiling(staff, m.id);
  lap('confirm');
});
